services:
  mongo:
    image: mongo:4.0.28
    init: true
    ports:
      - "27000:27017"
    volumes:
      - models_mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=localhost
      - MONGO_INITDB_ROOT_PASSWORD=localhost_psa
    networks:
      - app_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - MONGO_URI=${MONGO_URI}
      - OPENWEATHER_API_KEY=${OPENWEATHER_API_KEY}
      - NODE_ENV=${NODE_ENV}
    ports:
      - "8080:8000"
      - "6457:6457"
    command: ./entrypoint.sh
    volumes:
      - ./backend/sentry/source:/backend/sentry/source
      - ./backend/sentry/keys:/backend/sentry/keys
      - ./backend/harvest:/backend/harvest
      - ./backend/floodcast:/backend/floodcast
    networks:
      - app_network
      - support_network
    # Commented out so it doesn't wait for the local mongo
    # depends_on:
    #   - mongo

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend:/app
    ports:
      - "8501:8501"
    networks:
      - app_network

networks:
  app_network:
  support_network:

volumes:
  models_mongo_data:

